//------------------------------------------------------------------------------
// <auto-generated>
//     Este c贸digo se gener贸 a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//     Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class GUIAS_RESERVACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUIAS_RESERVACION()
        {
            this.GUIAS_ASIGNACION = new HashSet<GUIAS_ASIGNACION>();
        }

        [Display(Name = "N鷐ero:")]
        public string NUMERORESERVACION { get; set; }
        [Display(Name = "Nombre:")]
        public string NOMBRERESERVACION { get; set; }
        [Display(Name = "Pack:")]
        public Nullable<decimal> NUMEROPERSONAS { get; set; }

        public string HORAMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        [Display(Name = "Fecha:")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="(0:yyyy-MM-dd)")]
        public Nullable<System.DateTime> FECHA { get; set; }
        [Display(Name = "Hora:")]
        public string HORA { get; set; }
        [Display(Name = "Estaci髇:")]
        public string NOMBREESTACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_ASIGNACION> GUIAS_ASIGNACION { get; set; }
    }
}
