//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIAS_TELEFONO
    {
        [Required]
        [StringLength(9)]
        [Display(Name = "Cédula:")]
        public string CEDULAEMPLEADO { get; set; }

        [Required]
        [StringLength(11)]
        [Display(Name = "Teléfono:")]
        public string TELEFONO { get; set; }
    
        public virtual GUIAS_EMPLEADO GUIAS_EMPLEADO { get; set; }
    }
}
