//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;

    public partial class GUIAS_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUIAS_EMPLEADO()
        {
            this.GUIAS_ASIGNAINTERNO = new HashSet<GUIAS_ASIGNAINTERNO>();
            this.GUIAS_ASOCIAEXTERNO = new HashSet<GUIAS_ASOCIAEXTERNO>();
            this.GUIAS_TELEFONO = new HashSet<GUIAS_TELEFONO>();
        }

        [Required]
        [StringLength(9)]
        [Display(Name = "Cédula:")]
        public string CEDULA { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Nombre:")]
        public string NOMBREEMPLEADO { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Primer apellido:")]
        public string APELLIDO1 { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Segundo apellido:")]
        public string APELLIDO2 { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Email:")]
        public string EMAIL { get; set; }

        [Required]
        [StringLength(7)]
        [Display(Name = "Estado:")]
        public decimal ESTADO { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Dirección:")]
        public string DIRECCION { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Usuario:")]
        public string USUARIO { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Contraseña:")]
        public string CONTRASENA { get; set; }

        [Required]
        [Display(Name = "Tipo empleado:")]
        public decimal TIPOEMPLEADO { get; set; }

        [Required]
        [StringLength(55)]
        [Display(Name = "Nombre estación:")]
        public string NOMBREESTACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_ASIGNAINTERNO> GUIAS_ASIGNAINTERNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_ASOCIAEXTERNO> GUIAS_ASOCIAEXTERNO { get; set; }
        public virtual GUIAS_ESTACION GUIAS_ESTACION { get; set; }
        public virtual GUIAS_HORARIODISPONIBLE GUIAS_HORARIODISPONIBLE { get; set; }
        public virtual GUIAS_ROLDIASLIBRES GUIAS_ROLDIASLIBRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_TELEFONO> GUIAS_TELEFONO { get; set; }
    }
}
