//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIAS_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUIAS_EMPLEADO()
        {
            this.GUIAS_ASIGNAINTERNO = new HashSet<GUIAS_ASIGNAINTERNO>();
            this.GUIAS_ASOCIAEXTERNO = new HashSet<GUIAS_ASOCIAEXTERNO>();
            this.GUIAS_TELEFONO = new HashSet<GUIAS_TELEFONO>();
        }
    
        public string CEDULA { get; set; }
        public string NOMBREEMPLEADO { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public string DIRECCION { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string TIPOEMPLEADO { get; set; }
        public string NOMBREESTACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_ASIGNAINTERNO> GUIAS_ASIGNAINTERNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_ASOCIAEXTERNO> GUIAS_ASOCIAEXTERNO { get; set; }
        public virtual GUIAS_ESTACION GUIAS_ESTACION { get; set; }
        public virtual GUIAS_HORARIODISPONIBLE GUIAS_HORARIODISPONIBLE { get; set; }
        public virtual GUIAS_ROLDIASLIBRES GUIAS_ROLDIASLIBRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIAS_TELEFONO> GUIAS_TELEFONO { get; set; }
    }
}
