//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiasOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIAS_ASIGNACION
    {
        public string NOTASASOCIA { get; set; }
        public string CONFIRMACIONASOCIA { get; set; }
        public string NUMERORESERVACION { get; set; }
        public string TURNO { get; set; }
        public string CEDULAGUIA { get; set; }
    
        public virtual GUIAS_EMPLEADO GUIAS_EMPLEADO { get; set; }
        public virtual GUIAS_RESERVACION GUIAS_RESERVACION { get; set; }

        public GUIAS_ASIGNACION()
        {
        }
    }
}
